security:
  encoders:
    App\Entity\Person:
      algorithm: bcrypt
  providers:
    login_provider:
      entity:
        class: App\Entity\User
        property: loginname

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true

      form_login:
        login_path: login
        check_path: login
        provider: login_provider

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
     - { path: ^/profile, roles: ROLE_ADMIN }
     - { path: ^/profile, roles: ROLE_TRAINER }
     - { path: ^/profile, roles: ROLE_MEMBER }
     - { path: ^/profile, roles: ROLE_USER }
