<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOvJc04\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOvJc04/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOvJc04.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOvJc04\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOOvJc04\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OOvJc04',
    'container.build_id' => 'b3dee1ff',
    'container.build_time' => 1574841795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOvJc04');
